### ISSUE TITLE
unwrap() trips up my code

### ISSUE THREAD

**Issue by magnusmanske** [mattsse/crossref-rs#5]
Found it:
https://github.com/MattsSe/crossref-rs/blob/1fee67e1fbace7ff76ab61f0428e845f3fad67c3/src/response/mod.rs#L105

Can be replaced with a `?`, but I'm too lazy to fork and patch...

**Comment by mattsse** [comment]
Thanks!
Good catch.
I fixed this and published 0.2.1 on crates.io
